# Generated by Django 2.1.2 on 2018-10-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Clipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('location', models.CharField(max_length=100, verbose_name='书摘位置')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clipping.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='User_Clipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='添加时间')),
                ('clipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clipping.Clipping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clipping.User')),
            ],
        ),
    ]
