# Generated by Django 2.1.2 on 2018-10-24 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0002_book_clipping_user_user_clipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_clipping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
