# Generated by Django 2.1.2 on 2018-11-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0003_auto_20181024_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ASIN',
            field=models.CharField(max_length=10, null=True, verbose_name='ASIN'),
        ),
    ]
