# Generated by Django 2.0.9 on 2022-06-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0006_user_clipping_is_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=256, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=256, verbose_name='书名'),
        ),
    ]
